version: "3.9"

services:
    database:
        image: postgres
        volumes: "./tmp/db:/var/lib/postgres/data"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=matcha
            - POSTGRES_USER=matcha_admin
            - POSTGRES_PASSWORD=matcha_password
        networks: 
            - matcha
    backend:
        build:
            context: ./backend
            dockerfile: ./docker/backend/Dockerfile
        command: sh -c "sleep 10"
        volumes:
            - "./backend:/code"
        ports:
            - "8001:8001"
        depends_on: 
            - database
        networks: 
            - matcha
networks:
    matcha:
        driver: bridge